builds:
  - binary: pwg
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
release:
  prerelease: auto

universal_binaries:
  - replace: true
brews:
  - name: pwg
    homepage: https://github.com/drew-anello/random-pw-generator
    tap:
      owner: drew-anello
      name: homebrew-mybrewformulas
    commit_author:
      name: Drew Anello
      email: drew.anello@gmail.com

checksum:
  name_template: "checksum.txt"
